spring:
    application:
        name: spring-boot-oauth2-server
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
        
        
    datasource:
        url: jdbc:mysql://localhost:4306/oauth2_server
        username: root
        password: example
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header
#logging:
#    level: DEBUG
    # org.springframework.security: DEBUG

server:
    port: 8080
    error:
        whitelabel:
            enabled: false